- index.html
- Fixed typo in about section on the main page.
- "12th edition" to "13th edition"
- Update workshop count 
- Remove `Get Ticket` button
Signed-off-by: Abhishek Mishra <geekabhi@outlook.com>
> Updated about section, workshop count & removed "Get Ticket" button on the main page

- assets/js/main.js
- coc.html
- index.html
- Update conference date
- Add a new contact on the COC page
> Update conference date and coc page

- index.html
- Add `submit a talk` button on the main page
Signed-off-by: Abhishek Mishra <geekabhi@outlook.com>
> Add `submit a talk` button on main page

- data/tickets.yml
As Early bird tickets are sold out. We need to open these
tickets.
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>
> Enable regular, workshop and combo tickets

- data/communities.yml
More to be added later.
cc: @abhishekmishragithub
> Added FOSS United to outreach partner list

- layouts/about/single.html
> Added BoF and Poster Session info in About page

- data/hero.yml
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
> Remove the link for the talk submission

- data/tickets.yml
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>
> Open WorkShop and combo tickets

- data/hero.yml
BoF CFP deadline is over, removing the button from website
> Removing submit BOF proposal button

- content/faq.md
- data/nav.yml
CC: @raukadah @palnabarun @sayanchowdhury
> Add the faq page

- data/schedule.yml
- layouts/index.html
- layouts/partials/sections/schedule.html
- layouts/partials/sections/speakers.html
- static/css/style.css
This should be ready for filling up with the schedule. Please take care of the data structure format in the `.yml` file. The talks can be of three different types:
- talk : Takes 1/4th width of the schedule (i.e. one room)
- keynote: Entire row width along with speaker name
- extra: Entire row, without speaker name (for break, networking, etc.)
> Adding the conference schedule

- data/keynote_speakers.yml
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>
> Added company name for Luciano

- content/faq.md
As suggested in https://github.com/pythonindia/inpycon2021/pull/31#pullrequestreview-711028422
> Fix spelling mistakes in FAQ

- data/tickets.yml
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
> Added 05th sep regular/combo ticket closing date

- data/tickets.yml
- layouts/partials/sections/ticket.html
- Implements logic for showing sold-out status for workshops
- Mark regular, workshop, and combo tickets as sold
- Open late bird tickets
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
> Mark regular, workshop and combo tickets as sold & open late bird tickets

- data/nav.yml
- layouts/partials/header.html
'Schedule' button on header nav starts working properly after this fix.
Signed-off-by: Shashank Kumar (realslimshanky) <abc@shanky.xyz>
> Header nav fix

- data/nav.yml
- layouts/partials/header.html
Reverts pythonindia/inpycon2021#46
The changes break all navigation links for the site built with a subpath.
> Revert "Header nav fix"

- content/faq.md
> Add panelists to the ticketing faq question

- data/schedule.yml
- layouts/partials/sections/schedule.html
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
> Update button text for Calendar download button

- content/jobs.md
- data/nav.yml
- layouts/jobs/single.html
- created job board template
- integrated sheets api for data
> create job board template

- layouts/jobs/single.html
> update api url, migrate to v4 and netlify function

- data/footer.yml
- data/hero.yml
- data/nav.yml
- data/tickets.yml
This PR does the following
- Replaces ticket buttons with PPG
- Mentions Late Bird as Sold out
> [data] Removing tickets
